image:
  name: pulumi/pulumi:latest
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    - 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}'
    - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}'
    - 'PULUMI_ACCESS_TOKEN=${PULUMI_ACCESS_TOKEN}'

stages:
  - test

test:
  stage: test
  script:
    - echo "Test"
    - pulumi help
